# Generated by Django 5.2.4 on 2025-08-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phuahtu',
            field=models.CharField(default='hrelo', max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='satu',
            field=models.CharField(default='hrelo', max_length=255),
        ),
    ]
