# Generated by Django 5.2.4 on 2025-08-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0002_alter_data_phuahtu_alter_data_satu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phuahtu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='satu',
            field=models.CharField(max_length=255),
        ),
    ]
