# Generated by Django 5.2.4 on 2025-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0003_alter_data_phuahtu_alter_data_satu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='desc',
            field=models.TextField(),
        ),
    ]
