# Generated by Django 5.2.4 on 2025-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0004_alter_data_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
