# Generated by Django 5.2.4 on 2025-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0007_data_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='req',
        ),
    ]
